### ISSUE TITLE
Code of EVE Metric

### ISSUE THREAD

**Issue by Sarthak-100** [psyai-net/EmoTalk_release#19]
The repository does not provide the code of the Emotional Vertex Error (EVE) proposed in the paper. I wanted to know if it would be possible to provide the same.

**Comment by ZiqiaoPeng** [comment]
You can refer to the evaluation code of [CodeTalker](https://github.com/Doubiiu/CodeTalker/blob/main/main/cal_metric.py), and the vertex mask of VOCA can be obtained from the [FLAME website.](https://flame.is.tue.mpg.de/). EVE uses the vertices of eye and forehead.

**Comment by shaheryar1** [comment]
@ZiqiaoPeng  can you also explain the method used to convert Blendshapes to (5023*3) mesh vertices corresponding to the FLAME model?
