### ISSUE TITLE
RuntimeError: The shape of the 3D attn_mask is torch.Size([4, 104, 104]), but should be (416, 1, 1).

### ISSUE THREAD

**Issue by RujingD** [psyai-net/EmoTalk_release#2]
你好！model.py中151行报错：
RuntimeError: The shape of the 3D attn_mask is torch.Size([4, 104, 104]), but should be (416, 1, 1).
跑demo.py中一直出现维度错误的问题，请问应该修改哪里呢？

**Comment by ZiqiaoPeng** [comment]
可以提供更多信息吗？
