### ISSUE TITLE
Details about blendshape capturing

### ISSUE THREAD

**Issue by k8kiw** [psyai-net/EmoTalk_release#7]
Hello,
I'm very interested in the blendshape capturing method used for reconstructing the 3D-ETF.
Could you tell me how you capture the facial blendshapes from 2D videos?
Hope you reply, thanks.

**Comment by ZiqiaoPeng** [comment]
We use the ResNet model to implement this part, which we describe in the Appendix.E "Blendshape capture method".

**Comment by H-Liu1997** [comment]
will this ResNet model be released?  thanks!

**Comment by ZiqiaoPeng** [comment]
Sorry, this ResNet model will not be released.

**Comment by H-Liu1997** [comment]
It’s okay, thanks for the reply

**Comment by ThetaRgo** [comment]
> Sorry, this ResNet model will not be released.

你好，blendshape的标签顺序能否提供一下？从论文中图形中获取的顺序如下，不知道数据情况是不是跟这个确定一样，另外顺序与mediapipe的blendshape.task产生的标签是否一致。

1 | template
2 | browDownLeft
3 | browDownRight
4 | browInnerUp
5 | browOuterUpLeft
6 | browOuterUpRight
7 | cheekPuff
8 | cheekSquintLeft
9 | cheekSquintRight
10 | eyeBlinkLeft
11 | eyeBlinkRight
12 | eyeLookDownLeft
13 | eyeLookDownRight
14 | eyeLookInLeft
15 | eyeLookInRight
16 | eyeLookOutLeft
17 | eyeLookOutRight
18 | eyeLookUpLeft
19 | eyeLookUpRight
20 | eyeSquintLeft
21 | eyeSquintRight
22 | eyeWideLeft
23 | eyeWideRight
24 | jawForward
25 | jawLeft
26 | jawOpen
27 | jawRight
28 | mouthClose
29 | mouthDimpleLeft
30 | mouthDimpleRight
31 | mouthFrownLeft
32 | mouthFrownRight
33 | mouthFunnel
34 | mouthLeft
35 | mouthLowerDownLeft
36 | mouthLowerDownRight
37 | mouthRight
38 | mouthPressLeft
39 | mouthPressRight
40 | mouthPucker
41 | mouthRollLower
42 | mouthRollUpper
43 | mouthShrugLower
44 | mouthShrugUpper
45 | mouthSmileLeft
46 | mouthSmileRight
47 | mouthStretchLeft
48 | mouthStretchRight
49 | mouthUpperUpLeft
50 | mouthUpperUpRight
51 | noseSneerLeft
52 | noseSneerRight

**Comment by hrWong** [comment]
@ThetaRgo You can refer [here](https://github.com/psyai-net/EmoTalk_release/blob/5179b27b2fdd1ca27fcbfa6a3264a5ecfd51d524/render.py#L9)

**Comment by piwawa** [comment]
> > Sorry, this ResNet model will not be released.
> 
> 你好，blendshape的标签顺序能否提供一下？从论文中图形中获取的顺序如下，不知道数据情况是不是跟这个确定一样，另外顺序与mediapipe的blendshape.task产生的标签是否一致。
> 
> 1 | template 2 | browDownLeft 3 | browDownRight 4 | browInnerUp 5 | browOuterUpLeft 6 | browOuterUpRight 7 | cheekPuff 8 | cheekSquintLeft 9 | cheekSquintRight 10 | eyeBlinkLeft 11 | eyeBlinkRight 12 | eyeLookDownLeft 13 | eyeLookDownRight 14 | eyeLookInLeft 15 | eyeLookInRight 16 | eyeLookOutLeft 17 | eyeLookOutRight 18 | eyeLookUpLeft 19 | eyeLookUpRight 20 | eyeSquintLeft 21 | eyeSquintRight 22 | eyeWideLeft 23 | eyeWideRight 24 | jawForward 25 | jawLeft 26 | jawOpen 27 | jawRight 28 | mouthClose 29 | mouthDimpleLeft 30 | mouthDimpleRight 31 | mouthFrownLeft 32 | mouthFrownRight 33 | mouthFunnel 34 | mouthLeft 35 | mouthLowerDownLeft 36 | mouthLowerDownRight 37 | mouthRight 38 | mouthPressLeft 39 | mouthPressRight 40 | mouthPucker 41 | mouthRollLower 42 | mouthRollUpper 43 | mouthShrugLower 44 | mouthShrugUpper 45 | mouthSmileLeft 46 | mouthSmileRight 47 | mouthStretchLeft 48 | mouthStretchRight 49 | mouthUpperUpLeft 50 | mouthUpperUpRight 51 | noseSneerLeft 52 | noseSneerRight

请问你复现 Facial Blendshape Capture 成功了吗？

**Comment by hrWong** [comment]
@piwawa You can refer to the preprocessing of another [work](https://github.com/ZiqiaoPeng/SyncTalk/blob/main/data_utils/process.py) by the same author.

**Comment by 2hiTee** [comment]
> @piwawa You can refer to the preprocessing of another [work](https://github.com/ZiqiaoPeng/SyncTalk/blob/main/data_utils/process.py) by the same author.

However, the author in the new paper said they used the blendshape capturer in Emotalk, but since it is not open sourced, so they used Mediapipe instead(not well performed).
